//
//  PresetCollectionsInfo.swift
//  Album Covers
//
//  Created by Théo Arrouye on 1/10/21.
//

import Foundation
import UIKit
import SwiftUI


var allCollections : [Collection] = [
    // Scenes collection
    Collection("Moods", "Feelin' some kinda way?",
        [
            CoverProperties(topText: "Deep",
                  botText: "Space",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "aditya-vyas"),
            
            CoverProperties(topText: "Above It",
                  botText: "All",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "alex-perez"),
            
            CoverProperties(topText: "Stillness",
                  botText: "",
                  topPos: 150,
                  botPos: 1350,
                  topTextAlignment: .left,
                  botTextAlignment: .right,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "alex-wong"),
            
            
            CoverProperties(topText: "Alone Time",
                  botText: "",
                  topPos: 150,
                  botPos: 1350,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "andre-benz"),
            
            CoverProperties(topText: "Lost In",
                  botText: "Thought",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "becca-tapert"),
            
            CoverProperties(topText: "Stormy",
                  botText: "Nights",
                  topPos: 1150,
                  botPos: 1350,
                  topTextAlignment: .right,
                  botTextAlignment: .right,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "breno-machado"),
            
            CoverProperties(topText: "Dark and",
                  botText: "Gloomy",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "drew-beamer"),
            
            CoverProperties(topText: "New",
                  botText: "Experiences",
                  topPos: 1150,
                  botPos: 1350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "fallon-michael"),
            
            CoverProperties(topText: "",
                  botText: "DESTRUCTION",
                  topPos: 150,
                  botPos: 1250,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 190,
                  botFontSize: 190,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  topXOffset: 0,
                  botXOffset: 0,
                  textSidePadding: 0,
                  backgroundImgURL: "hizir-kaya"),
            
            
            CoverProperties(topText: "EUPHORIA",
                  botText: "",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "jr-korpa"),
            
            CoverProperties(topText: "COUCH",
                  botText: "POTATO",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "martin-pechy"),
            
            CoverProperties(topText: "Wise &",
                  botText: "Sage",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "minh-pham"),
            
            CoverProperties(topText: "All",
                  botText: "Natural",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "paul-carmona"),
            
            CoverProperties(topText: "Winding",
                  botText: "Roads",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "rodrigo-abreu"),
            
            CoverProperties(topText: "Grunge",
                  botText: "Mix",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "scott-rodgerson"),
            
            CoverProperties(topText: "Wonderment",
                  botText: "",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  topXOffset: 10,
                  botXOffset: 10,
                  textSidePadding: 10,
                  backgroundImgURL: "terry-matthews"),
            
            CoverProperties(topText: "CASHOUT",
                  botText: "CASHOUT",
                  topPos: 730,
                  botPos: 720,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.green,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "sharon-mccutcheon"),
        ]
    ),
    
    // Abstract collection
    Collection("Abstract", "Woaaaahhh... Trippy.",
        [
            CoverProperties(topText: "Top 25",
                  botText: "Most Played",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "adrien-converse"),
            
            CoverProperties(topText: "Favorites",
                  botText: "Mix",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "adrien-converse-2"),
            
            CoverProperties(topText: "Top Songs",
                  botText: "2020",
                  topPos: 650,
                  botPos: 900,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "bia-andrade"),
            
            CoverProperties(topText: "Recently",
                  botText: "Played",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "daniel-olah"),
            
            CoverProperties(topText: "New",
                  botText: "Music",
                  topPos: 1150,
                  botPos: 1350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "daniel-olah-2"),
            
            CoverProperties(topText: "Recently",
                  botText: "Added",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "daniel-olah-3"),
            
            CoverProperties(topText: "Throwback",
                  botText: "Mix",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "daniele-levis-pelusi"),
            
            CoverProperties(topText: "Chill",
                  botText: "Mix",
                  topPos: 150,
                  botPos: 350,
                  topTextAlignment: .right,
                  botTextAlignment: .right,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "daniele-levis-pelusi-2"),
            
            CoverProperties(topText: "Party",
                  botText: "Mix",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .right,
                  botTextAlignment: .right,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "ilya-lix"),
            
            
            CoverProperties(topText: "Fresh",
                  botText: "Discoveries",
                  topPos: 1150,
                  botPos: 1350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "joel-filipe"),
            
            
            CoverProperties(topText: "Lost",
                  botText: "Sounds",
                  topPos: 150,
                  botPos: 350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "lucas-benjamin"),
            
            CoverProperties(topText: "Lo-fi",
                  botText: "Beats",
                  topPos: 150,
                  botPos: 350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "lucas-benjamin-2"),
            
            
            CoverProperties(topText: "Trap",
                  botText: "Remixes",
                  topPos: 150,
                  botPos: 350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "mohammad-alizade"),
            
            
            CoverProperties(topText: "Pop",
                  botText: "Hits",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "pawel-czerwinski"),
            
            CoverProperties(topText: "Rap",
                  botText: "Vibes",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "pawel-czerwinski-2"),
            
            CoverProperties(topText: "Good",
                  botText: "Times",
                  topPos: 650,
                  botPos: 900,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "pawel-czerwinski-3"),
            
            CoverProperties(topText: "sadboi",
                   botText: "hours",
                   topPos: 200,
                   botPos: 400,
                   topTextAlignment: .center,
                   botTextAlignment: .center,
                   topFontName: "Helvetica Bold",
                   botFontName: "Helvetica",
                   topFontSize: 200,
                   botFontSize: 200,
                   topFontColor: UIColor.white,
                   botFontColor: UIColor.white,
                   topXOffset: 20,
                   botXOffset: 20,
                   textSidePadding: 10,
                   backgroundImgURL: "pawel-czerwinski-4"),
            
            CoverProperties(topText: "Celebratory",
                  botText: "Mix",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "pawel-czerwinski-5"),
            
            CoverProperties(topText: "Poisoned",
                  botText: "Chalice",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "pawel-czerwinski-6"),
            
            CoverProperties(topText: "FEELIN'",
                  botText: "GOOD",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "rodion-kutsaev"),
            
            CoverProperties(topText: "90's CLASSICS",
                  botText: "& MORE",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 180,
                  botFontSize: 180,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  textSidePadding: 50,
                  backgroundImgURL: "rodion-kutsaev-2")
        ]
    ),
    
    // Geometric collection
    Collection("Geometric", "Not your mama's shapes.",
        [
            
            CoverProperties(topText: "Scales",
                  botText: "",
                  topPos: 775,
                  botPos: 1350,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Papyrus",
                  botFontName: "Papyrus",
                  topFontSize: 248,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "andrew-ridley"),
            
            
            CoverProperties(topText: "Laser",
                  botText: "Show",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "ash-edmonds"),
            
            CoverProperties(topText: "",
                  botText: "Cubbies",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "ben-neale"),
            
            CoverProperties(topText: "Windows",
                  botText: "",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "daniel-von-appen"),
            
            CoverProperties(topText: "Infinite",
                  botText: "Loop",
                  topPos: 650,
                  botPos: 900,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "efe-kurnaz"),
            
            CoverProperties(topText: "Tunnel",
                  botText: "Vision",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "joel-fulgencio"),
            
            CoverProperties(topText: "Jungle",
                  botText: "Gym",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "john-morell"),
            
            CoverProperties(topText: "",
                  botText: "Ripples",
                  topPos: 1150,
                  botPos: 1350,
                  topTextAlignment: .right,
                  botTextAlignment: .right,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "ricardo-gomez-angel"),
            
            CoverProperties(topText: "Winding",
                  botText: "Trails",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "ricardo-gomez-angel-2"),
            
            CoverProperties(topText: "Psychadelic",
                  botText: "Sounds",
                  topPos: 650,
                  botPos: 900,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "ricardo-gomez-angel-3"),
            
            CoverProperties(topText: "Spotted",
                  botText: "Glass",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "scott-webb"),
            
            CoverProperties(topText: "Sunny",
                  botText: "Winston",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "scott-webb-2"),
            
            CoverProperties(topText: "Tiny",
                  botText: "Houses",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "scott-webb-3"),
            
            CoverProperties(topText: "Cityscape",
                  botText: "",
                  topPos: 600,
                  botPos: 1350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  topXOffset: 10,
                  botXOffset: 10,
                  textSidePadding: 10,
                  backgroundImgURL: "simone-hutsch"),
            
            CoverProperties(topText: "Short",
                  botText: "Stack",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "simone-hutsch-2"),
            
            CoverProperties(topText: "",
                  botText: "Gridiron",
                  topPos: 1150,
                  botPos: 1350,
                  topTextAlignment: .right,
                  botTextAlignment: .right,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "zara-walker"),
            
            
            
        ]
    ),
    
    // Love collection
    Collection("Love", "For playlists about that special something.",
        [
            CoverProperties(topText: "Emo",
                  botText: "Hours",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "alexandru-acea"),
            
            CoverProperties(topText: "Sunset",
                  botText: "Lover",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Papyrus",
                  botFontName: "Papyrus",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "aziz-acharki"),
            
            CoverProperties(topText: "Gentle Soul",
                  botText: "",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 200,
                  botFontSize: 200,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  topXOffset: 30,
                  textSidePadding: 10,
                  backgroundImgURL: "bart-larue"),

            CoverProperties(topText: "Always the",
                  botText: "Vibe",
                  topPos: 1150,
                  botPos: 1350,
                  topTextAlignment: .right,
                  botTextAlignment: .right,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "belinda-fewings"),
            
            CoverProperties(topText: "Unforgettable",
                  botText: "",
                  topPos: 225,
                  botPos: 350,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 200,
                  botFontSize: 200,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  topXOffset: 30,
                  textSidePadding: 10,
                  backgroundImgURL: "debby-hudson"),
            
            CoverProperties(topText: "",
                  botText: "Memories",
                  topPos: 1050,
                  botPos: 1250,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "elias-maurer"),
           

            CoverProperties(topText: "New",
                  botText: "Fire",
                  topPos: 150,
                  botPos: 350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "fadi-xd"),
            
            
            CoverProperties(topText: "Explosive",
                  botText: "Feelings",
                  topPos: 150,
                  botPos: 1350,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "jamie-street"),
            
            CoverProperties(topText: "Beach",
                  botText: "Babe",
                  topPos: 150,
                  botPos: 350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "lea-khreiss"),
            
            CoverProperties(topText: "",
                  botText: "Homebody",
                  topPos: 1150,
                  botPos: 1250,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "nick-fewings"),
            
            CoverProperties(topText: "Lost",
                  botText: "Boy",
                  topPos: 300,
                  botPos: 1200,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "nicola-fioravanti"),
            
            CoverProperties(topText: "",
                  botText: "Sleepless",
                  topPos: 150,
                  botPos: 1250,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "ryan-o-niel")
        ]
    ),
    
    // Seasons collection
    Collection("Seasons", "It's always that time of year.",
        [
            // Winter
            CoverProperties(topText: "Winter",
                  botText: "Whispers",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "josh-hild"),
            
            CoverProperties(topText: "Snowflakes",
                  botText: "",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "aaron-burden"),
            
            CoverProperties(topText: "Snowman",
                  botText: "Season",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "shelley-pauls"),
            
            CoverProperties(topText: "Peace &",
                  botText: "Quiet",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "adam-chang"),
            
            CoverProperties(topText: "Chilled",
                  botText: "Bones",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "jorge-garhe"),
            
            // Spring
            CoverProperties(topText: "Easter",
                  botText: "Eggs",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "annie-spratt"),
            
            CoverProperties(topText: "Spring",
                  botText: "Feelings",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "arno-smit"),
            
            CoverProperties(topText: "Buttercup",
                  botText: "",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "tim-gouw"),
            
            CoverProperties(topText: "Spring",
                  botText: "Critters",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "boris-smokrovic"),
            
            CoverProperties(topText: "Child of",
                  botText: "Spring",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "karl-fredrickson"),
            
            CoverProperties(topText: "Easter",
                  botText: "Surprise",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "laurentiu-iordache"),
            
            CoverProperties(topText: "Blooming",
                  botText: "",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "masaaki-komori"),
            
            CoverProperties(topText: "Spring",
                  botText: "Sunshine",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "robin-mathlener"),
            

            
            // Summer
            CoverProperties(topText: "Sound",
                  botText: "Waves",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "shifaaz-shamoon"),
            
            CoverProperties(topText: "Summer",
                  botText: "Haze",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "arty-n"),
            
            CoverProperties(topText: "POOL",
                  botText: "PARTY",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "boxed-water"),
            
            CoverProperties(topText: "SUMMER",
                  botText: "VIBES",
                  topPos: 200,
                  botPos: 450,
                  topTextAlignment: .center,
                  botTextAlignment: .center,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 200,
                  botFontSize: 200,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  topXOffset: 20,
                  textSidePadding: 10,
                  backgroundImgURL: "mateo-giraud"),
            
            // Fall
            CoverProperties(topText: "Falling",
                  botText: "Slowly",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "autumn-mott-rodeheaver"),
            
            CoverProperties(topText: "Colors of",
                  botText: "Fall",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "chris-lawton"),
            
            CoverProperties(topText: "Serene",
                  botText: "Fall",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "jeremy-thomas"),
            
            CoverProperties(topText: "Eerie",
                  botText: "Evening",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "patrick-tomasso"),
            
            CoverProperties(topText: "Hallowed",
                  botText: "Halls",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "daniel-lincoln"),
            
            CoverProperties(topText: "Spoopy",
                  botText: "Kitty",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "saso-tusar"),
            
        ]
    ),
    
    // Country collection
    Collection("Country", "Time to dust those boots off!",
        [
            // Country
            
            // [barn couple] (standard top left, large Helvetica)
            CoverProperties(topText: "Ride or",
                  botText: "Die",
                  topPos: 625,
                  botPos: 850,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "austin-paquette"),
            
            // [feet over creek] (bottom right to mix it up)
            CoverProperties(topText: "Peaceful",
                  botText: "Acoustic",
                  topPos: 1150,
                  botPos: 1350,
                  topTextAlignment: .right,
                  botTextAlignment: .right,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.black,
                  botFontColor: UIColor.black,
                  backgroundImgURL: "blake-cheek"),
            
            // [truck outdoors]
            CoverProperties(topText: "Outdoors",
                  botText: "",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Baskerville-SemiBoldItalic",
                  botFontName: "Baskerville",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "brad-mills"),
            
            // [guitar man]
            CoverProperties(topText: "",
                  botText: "Rock On",
                  topPos: 150,
                  botPos: 1350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "catalin-pop"),
            
            // [lady with hat]
            CoverProperties(topText: "Cowgirl",
                  botText: "Hour",
                  topPos: 1150,
                  botPos: 1350,
                  topTextAlignment: .right,
                  botTextAlignment: .right,
                  topFontName: "Papyrus",
                  botFontName: "Papyrus",
                  topFontSize: 248,
                  botFontSize: 248,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "clem-onojeghuo"),
            
            // [horses in field]
            CoverProperties(topText: "Prairie",
                  botText: "Vibes",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "joseph-daniel"),
            
            // [lady with dogs]
            CoverProperties(topText: "",
                  botText: "Outlaw",
                  topPos: 150,
                  botPos: 1350,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "patrick-hendry"),
            
            // [boots knockin, kicked back in chair]
            CoverProperties(topText: "Kickin'",
                  botText: "Back",
                  topPos: 150,
                  botPos: 375,
                  topTextAlignment: .left,
                  botTextAlignment: .left,
                  topFontName: "Helvetica Bold",
                  botFontName: "Helvetica Bold",
                  topFontSize: 216,
                  botFontSize: 216,
                  topFontColor: UIColor.white,
                  botFontColor: UIColor.white,
                  backgroundImgURL: "rachel-coyne"),
            
            
            // Hip Hop
            
            
            // Pop
            
        ]
    ),
    
]
